name: Main Branch CI/CD

on:
    push:
        branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
          
      - name: Install system dependencies
        run: |
            sudo apt-get install -y python3-venv
    
      - name: Create and activate venv
        run: |
            python -m venv venv
            source venv/bin/activate
    
      - name: Install dependencies
        run: |
            pip install -r requirements.txt

      - name: check pytest version
        run: pytest --version

      - name: List venv contents
        run: |
          ls -R venv

      - name: List npmVersionRepo directories
        run: ls -R
      
      - name: copy contents from layer to venv
        run: cp -r layers/mercuryReusableMethods venv/lib/python3.12/site-packages/
      
      - name: List venv contents
        run: |
          ls -R venv

      - name: Unit test
        run: |
          command -v python
          pytest tests/unit --cov=. --cov-report xml

      # - name: unit tests
      #   run: make unit
    
      - name: Display Python directories
        run: |
            echo "Previously installed Python directories:"
            echo "-------------------------"
            python -m site
            echo "-------------------------"
            echo "New virtual environment (venv) directories:"
            echo "-------------------------"
            python -m site
            echo "-------------------------"

      # - name: run 
      #   run: |
      #     python3 -m pip install --upgrade pip
      #     python3 -m pip install -r requirements.txt

      # # - name: Remove existing venv
      # #   run: make clean-venv

      # # - name: Create a new venv
      # #   run: make venv

      # # - name: activate venv
      # #   run: source ./venv/bin/activate

      # - name: check pytest version
      #   run: pytest --version

      # - name: run unit test cases
      #   run:  make unit

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[your-aws-profile]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets['AWS_ACCESS_KEY_ID'] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets['AWS_SECRET_ACCESS_KEY'] }}


      - name: Deploy to AWS
        run: make deploy
        env:
          AWS_PROFILE: your-aws-profile